<a href="https://colab.research.google.com/github/Nolan-Jgr/golf-analytics-project/blob/main/notebooks/01_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Golf Analytics Project
## Phase 1: Data Cleaning & Preparation

**Author:** Nolan Jaeger  
**Dataset:** Fictional Golf Performance Dataset  
**Records:** 25,000  
**Tools:** Python, Pandas, Google Colab

### Project Objective

The objective of this project is to analyze fictional golf performance data
to identify factors associated with player performance, tournament outcomes,
and earnings.

This first phase focuses on inspecting, cleaning, validating, and preparing
the dataset for further analysis.

## 1. Project Overview

This project analyzes fictional golf performance data containing information
about players, tournaments, courses, scoring, driving performance, putting,
birdies, bogeys, strokes gained, and earnings.

The overall project will progress through several stages:

1. Data Cleaning & Preparation
2. Exploratory Data Analysis
3. SQL Analysis
4. Dashboard Development
5. Predictive Modeling
6. Business Insights & Recommendations

### Phase 1 Objective

The goal of Phase 1 is to ensure that the dataset is:

- Complete
- Consistent
- Properly formatted
- Free of duplicate records
- Within reasonable values
- Ready for analysis

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

## 2. Load Dataset

The dataset contains 25,000 fictional golf performance records.

The raw dataset will be loaded into a Pandas DataFrame for inspection and
cleaning.

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Fictional_Golf_Project/Data/Fictional_Golf_Dataset_25000_Rows_Original.csv")
df.head()

,PlayerID,FirstName,LastName,Age,Tournament,Season,Round,Course,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings
0,328,Jordan,Smith,22,Spring Classic,2025,3,Cedar Hills,70,311.1,4,7,27,3,4,69,1.02,16894.88
1,288,Casey,Hall,36,Lakes Championship,2025,4,Pine Ridge,70,295.6,10,11,28,2,1,76,4.57,6699.68
2,173,Jordan,Johnson,45,Lakes Championship,2025,4,Cedar Hills,70,294.5,11,14,25,6,0,73,0.52,14671.47
3,425,Cameron,Wilson,19,River Open,2025,2,Lakeview,72,330.2,5,12,28,7,5,66,3.34,10359.10
4,84,Sam,Wilson,40,Spring Classic,2025,2,Cedar Hills,72,280.3,7,8,31,6,2,72,4.90,3656.65

### Dataset Dimensions

First, I will verify the number of observations and variables in the dataset.

In [7]:
df.shape

(25000, 18)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PlayerID            25000 non-null  int64
 1   FirstName           25000 non-null  object
 2   LastName            25000 non-null  object
 3   Age                 25000 non-null  int64
 4   Tournament          25000 non-null  object
 5   Season              25000 non-null  int64
 6   Round               25000 non-null  int64
 7   Course              25000 non-null  object
 8   CoursePar           25000 non-null  int64
 9   DriveDistance       25000 non-null  float64
 10  FairwaysHit         25000 non-null  int64
 11  GIR                 25000 non-null  int64
 12  Putts               25000 non-null  int64
 13  Birdies             25000 non-null  int64
 14  Bogeys              25000 non-null  int64
 15  Score               25000 non-null  int64
 16  StrokesGainedTotal  25000 non-null  float64
 17  Earnings            25000 non-null  float64
dtypes: float64(3), int64(11), object(4)
memory usage: 3.4+ MB

## 3.Data Quality Assessment
### Missing Value

Missing values can change the outcome of calculations and further statistical analysis. I will identify the number of missing values in each column. After this, I will decide if any further cleaning is required.

In [9]:
df.isnull().sum()

PlayerID              0
FirstName             0
LastName              0
Age                   0
Tournament            0
Season                0
Round                 0
Course                0
CoursePar             0
DriveDistance         0
FairwaysHit           0
GIR                   0
Putts                 0
Birdies               0
Bogeys                0
Score                 0
StrokesGainedTotal    0
Earnings              0
dtype: int64

In [10]:
df.isnull().sum().sum()

np.int64(0)

There are no missing vlaues.

### Duplicate Records

Since duplicates can cause data to be counted more than once, I will chech for duplicate rows before continuing.

In [11]:
df.duplicated().sum()

np.int64(0)

No duplicates records were found within the dataset. If there were, I would have proceeded to drop them from the dataset.

## 4. Descriptive Statistics

Descriptive statistics provide an initial understanding of the numerical variables in the dataset and can help identify potentially unrealistic values.

In [12]:
df.describe()

,PlayerID,Age,Season,Round,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings
count,25000.000000,25000.000000,25000.0,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,250.282160,31.471400,2025.0,2.501760,70.999880,294.804636,9.025600,11.991240,30.019760,3.984120,2.991040,70.989640,-0.011954,12423.747346
std,144.614353,8.054997,0.0,1.116444,0.813478,17.989249,3.169275,3.734354,3.755307,2.582939,2.003018,4.969431,2.894078,8306.873082
min,1.000000,18.000000,2025.0,1.000000,70.000000,208.800000,4.000000,6.000000,24.000000,0.000000,0.000000,62.000000,-5.000000,0.000000
25%,125.000000,24.000000,2025.0,2.000000,70.000000,282.800000,6.000000,9.000000,27.000000,2.000000,1.000000,67.000000,-2.530000,5983.530000
50%,249.000000,31.000000,2025.0,3.000000,71.000000,294.800000,9.000000,12.000000,30.000000,4.000000,3.000000,71.000000,0.000000,12105.105000
75%,376.000000,38.000000,2025.0,3.000000,72.000000,306.800000,12.000000,15.000000,33.000000,6.000000,5.000000,75.000000,2.470000,18165.857500
max,500.000000,45.000000,2025.0,4.000000,72.000000,380.300000,14.000000,18.000000,36.000000,8.000000,6.000000,80.000000,5.000000,50146.300000

In [13]:
df["Age"].describe()

count    25000.000000
mean        31.471400
std          8.054997
min         18.000000
25%         24.000000
50%         31.000000
75%         38.000000
max         45.000000
Name: Age, dtype: float64

In [14]:
df["DriveDistance"].describe()

count    25000.000000
mean       294.804636
std         17.989249
min        208.800000
25%        282.800000
50%        294.800000
75%        306.800000
max        380.300000
Name: DriveDistance, dtype: float64

In [15]:
df["Putts"].describe()

count    25000.000000
mean        30.019760
std          3.755307
min         24.000000
25%         27.000000
50%         30.000000
75%         33.000000
max         36.000000
Name: Putts, dtype: float64

In [16]:
df["Score"].describe()

count    25000.000000
mean        70.989640
std          4.969431
min         62.000000
25%         67.000000
50%         71.000000
75%         75.000000
max         80.000000
Name: Score, dtype: float64

In [17]:
df["Birdies"].describe()

count    25000.000000
mean         3.984120
std          2.582939
min          0.000000
25%          2.000000
50%          4.000000
75%          6.000000
max          8.000000
Name: Birdies, dtype: float64

In [18]:
df["Bogeys"].describe()

count    25000.000000
mean         2.991040
std          2.003018
min          0.000000
25%          1.000000
50%          3.000000
75%          5.000000
max          6.000000
Name: Bogeys, dtype: float64

Invalid Ages

In [19]:
df[df["Age"] < 18]

Empty DataFrame
Columns: [PlayerID, FirstName, LastName, Age, Tournament, Season, Round, Course, CoursePar, DriveDistance, FairwaysHit, GIR, Putts, Birdies, Bogeys, Score, StrokesGainedTotal, Earnings]
Index: []

Unrealistic driving distances

In [22]:
df[(df["DriveDistance"] < 200) | (df["DriveDistance"] > 400)]

Empty DataFrame
Columns: [PlayerID, FirstName, LastName, Age, Tournament, Season, Round, Course, CoursePar, DriveDistance, FairwaysHit, GIR, Putts, Birdies, Bogeys, Score, StrokesGainedTotal, Earnings]
Index: []

Invalid Putts

In [23]:
df[(df["Putts"] < 18) | (df["Putts"] > 50)]

Empty DataFrame
Columns: [PlayerID, FirstName, LastName, Age, Tournament, Season, Round, Course, CoursePar, DriveDistance, FairwaysHit, GIR, Putts, Birdies, Bogeys, Score, StrokesGainedTotal, Earnings]
Index: []

Invalid birdie counts

In [24]:
df[(df["Birdies"] < 0) | (df["Birdies"] > 18)]

Empty DataFrame
Columns: [PlayerID, FirstName, LastName, Age, Tournament, Season, Round, Course, CoursePar, DriveDistance, FairwaysHit, GIR, Putts, Birdies, Bogeys, Score, StrokesGainedTotal, Earnings]
Index: []

Invalid bogey Counts

In [25]:
df[(df["Bogeys"] < 0) | (df["Bogeys"] > 18)]

Empty DataFrame
Columns: [PlayerID, FirstName, LastName, Age, Tournament, Season, Round, Course, CoursePar, DriveDistance, FairwaysHit, GIR, Putts, Birdies, Bogeys, Score, StrokesGainedTotal, Earnings]
Index: []

## 5. Additional Variables

Additional variables will be created from the existing data to make the dataset more useful for analysis.

Score to par

In [26]:
df["ScoreToPar"] = df["Score"] - df['CoursePar']

Birdie Percentage

In [27]:
df["BirdiePct"] = df["Birdies"] / 18

Bogey Percentage

In [28]:
df["BogeyPct"] = df["Bogeys"] / 18

Earnings per Stroke

In [30]:
df["EarningsPerStroke"] = df["Earnings"] / df["Score"]

In [31]:
df[
    [
        "Score",
        "CoursePar",
        "ScoreToPar",
        "Birdies",
        "BirdiePct",
        "Bogeys",
        "BogeyPct",
        "Earnings",
        "EarningsPerStroke"
    ]
].head(10)

,Score,CoursePar,ScoreToPar,Birdies,BirdiePct,Bogeys,BogeyPct,Earnings,EarningsPerStroke
0,69,70,-1,3,0.166667,4,0.222222,16894.88,244.853333
1,76,70,6,2,0.111111,1,0.055556,6699.68,88.153684
2,73,70,3,6,0.333333,0,0.000000,14671.47,200.979041
3,66,72,-6,7,0.388889,5,0.277778,10359.10,156.956061
4,72,72,0,6,0.333333,2,0.111111,3656.65,50.786806
5,69,70,-1,3,0.166667,5,0.277778,13937.99,201.999855
6,69,70,-1,3,0.166667,1,0.055556,23891.32,346.251014
7,69,72,-3,8,0.444444,6,0.333333,15429.42,223.614783
8,74,72,2,2,0.111111,4,0.222222,12608.16,170.380541
9,73,70,3,7,0.388889,0,0.000000,6138.21,84.085068

## 6. Final Data Quality Check

After cleaning, validating, and making any additional changes, the dataset will be reviewed one final time.

In [33]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Records:", df.duplicated().sum())

Rows: 25000
Columns: 22
Missing Values: 0
Duplicate Records: 0

## 7. Export Cleaned Dataset

The now cleaned dataset will be exported as a separate CSV file and used for the remaining phases of the project.

In [34]:
df.to_csv("/content/drive/MyDrive/Fictional_Golf_Project/Data/Fictional_Golf_Dataset_25000_Rows_Cleaned.csv", index=False)

# Phase 1 Conclusion

The fictional golf dataset was successfully inspected, validated, and
prepared for analysis.

### Completed Tasks

- Loaded the 25,000-row dataset
- Inspected the dataset structure
- Reviewed data types
- Checked for missing values
- Checked for duplicate records
- Reviewed descriptive statistics
- Validated key golf performance variables
- Created calculated performance metrics
- Performed a final data quality check
- Exported the cleaned dataset

The resulting dataset is ready for exploratory data analysis and SQL-based
analysis in the next phase.

### Next Phase

**Phase 2: SQL Analysis**

The next phase will use SQL to answer business and performance questions
about players, tournaments, scoring, and earnings.