<a href="https://colab.research.google.com/github/Nolan-Jgr/golf-analytics-project/blob/main/notebooks/02_Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Golf Analytics Project
## Phase 2: Exploratory Data Analysis

### Objective
The purpose of this phase is to explore the cleaned golf dataset and identify
patterns and relationships between player performance, scoring, tournament
performance, and earnings.

The analysis will use descriptive statistics and data visualization to
develop insights that will guide the SQL analysis and dashboard development
in later phases.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [9]:
df = pd.read_csv("/content/drive/MyDrive/Fictional_Golf_Project/Data/Fictional_Golf_Dataset_25000_Rows_Cleaned.csv")
df.head()

,PlayerID,FirstName,LastName,Age,Tournament,Season,Round,Course,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings,ScoreToPar,BirdiePct,BogeyPct,EarningsPerStroke
0,328,Jordan,Smith,22,Spring Classic,2025,3,Cedar Hills,70,311.1,4,7,27,3,4,69,1.02,16894.88,-1,0.166667,0.222222,244.853333
1,288,Casey,Hall,36,Lakes Championship,2025,4,Pine Ridge,70,295.6,10,11,28,2,1,76,4.57,6699.68,6,0.111111,0.055556,88.153684
2,173,Jordan,Johnson,45,Lakes Championship,2025,4,Cedar Hills,70,294.5,11,14,25,6,0,73,0.52,14671.47,3,0.333333,0.000000,200.979041
3,425,Cameron,Wilson,19,River Open,2025,2,Lakeview,72,330.2,5,12,28,7,5,66,3.34,10359.10,-6,0.388889,0.277778,156.956061
4,84,Sam,Wilson,40,Spring Classic,2025,2,Cedar Hills,72,280.3,7,8,31,6,2,72,4.90,3656.65,0,0.333333,0.111111,50.786806

In [10]:
df.shape

(25000, 22)

##Overview

In [11]:
df.describe()

,PlayerID,Age,Season,Round,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings,ScoreToPar,BirdiePct,BogeyPct,EarningsPerStroke
count,25000.000000,25000.000000,25000.0,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,250.282160,31.471400,2025.0,2.501760,70.999880,294.804636,9.025600,11.991240,30.019760,3.984120,2.991040,70.989640,-0.011954,12423.747346,-0.010240,0.221340,0.166169,175.784473
std,144.614353,8.054997,0.0,1.116444,0.813478,17.989249,3.169275,3.734354,3.755307,2.582939,2.003018,4.969431,2.894078,8306.873082,4.903963,0.143497,0.111279,118.424760
min,1.000000,18.000000,2025.0,1.000000,70.000000,208.800000,4.000000,6.000000,24.000000,0.000000,0.000000,62.000000,-5.000000,0.000000,-8.000000,0.000000,0.000000,0.000000
25%,125.000000,24.000000,2025.0,2.000000,70.000000,282.800000,6.000000,9.000000,27.000000,2.000000,1.000000,67.000000,-2.530000,5983.530000,-4.000000,0.111111,0.055556,84.336375
50%,249.000000,31.000000,2025.0,3.000000,71.000000,294.800000,9.000000,12.000000,30.000000,4.000000,3.000000,71.000000,0.000000,12105.105000,0.000000,0.222222,0.166667,170.119731
75%,376.000000,38.000000,2025.0,3.000000,72.000000,306.800000,12.000000,15.000000,33.000000,6.000000,5.000000,75.000000,2.470000,18165.857500,4.000000,0.333333,0.277778,256.017051
max,500.000000,45.000000,2025.0,4.000000,72.000000,380.300000,14.000000,18.000000,36.000000,8.000000,6.000000,80.000000,5.000000,50146.300000,8.000000,0.444444,0.333333,737.445588

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PlayerID            25000 non-null  int64
 1   FirstName           25000 non-null  object
 2   LastName            25000 non-null  object
 3   Age                 25000 non-null  int64
 4   Tournament          25000 non-null  object
 5   Season              25000 non-null  int64
 6   Round               25000 non-null  int64
 7   Course              25000 non-null  object
 8   CoursePar           25000 non-null  int64
 9   DriveDistance       25000 non-null  float64
 10  FairwaysHit         25000 non-null  int64
 11  GIR                 25000 non-null  int64
 12  Putts               25000 non-null  int64
 13  Birdies             25000 non-null  int64
 14  Bogeys              25000 non-null  int64
 15  Score               25000 non-null  int64
 16  StrokesGainedTotal  25000 non-null  float64
 17  Earnings            25000 non-null  float64
 18  ScoreToPar          25000 non-null  int64
 19  BirdiePct           25000 non-null  float64
 20  BogeyPct            25000 non-null  float64
 21  EarningsPerStroke   25000 non-null  float64
dtypes: float64(6), int64(12), object(4)
memory usage: 4.2+ MB

In [13]:
df.nunique()

PlayerID                500
FirstName                10
LastName                 10
Age                      28
Tournament                5
Season                    1
Round                     4
Course                    5
CoursePar                 3
DriveDistance          1087
FairwaysHit              11
GIR                      13
Putts                    13
Birdies                   9
Bogeys                    7
Score                    19
StrokesGainedTotal     1001
Earnings              22643
ScoreToPar               17
BirdiePct                 9
BogeyPct                  7
EarningsPerStroke     22726
dtype: int64

## Overall Performance

Before examining individual players and tournaments, I will establish baseline performance metrics for the entire dataset.

In [15]:
print("Average Score:", round(df["Score"].mean(),2))
print("Average Score to Par:", round(df["ScoreToPar"].mean(), 2))
print("Average Driving Distance:", round(df["DriveDistance"].mean(), 2))
print("Average Putts:", round(df["Putts"].mean(), 2))
print("Average GIR:", round(df["GIR"].mean(), 2))
print("Average Birdies:", round(df["Birdies"].mean(), 2))
print("Average Bogeys:", round(df["Bogeys"].mean(), 2))
print("Average Earnings:", round(df["Earnings"].mean(), 2))
print("Average Strokes Gained:", round(df["StrokesGainedTotal"].mean(), 2))

Average Score: 70.99
Average Score to Par: -0.01
Average Driving Distance: 294.8
Average Putts: 30.02
Average GIR: 11.99
Average Birdies: 3.98
Average Bogeys: 2.99
Average Earnings: 12423.75
Average Strokes Gained: -0.01